services:
  - type: web
    name: p2p-backend
    runtime: python
    pythonVersion: 3.11
    rootDir: backend
    buildCommand: bash build.sh
    startCommand: gunicorn vignesh3d.wsgi --bind 0.0.0.0:$PORT --workers 2
    envVars:
      - key: DEBUG
        value: false
      - key: PYTHON_VERSION
        value: 3.11.10
      - key: PIP_INSTALL_TIMEOUT
        value: 600
      - key: DATABASE_URL
        value: postgresql://p2p_shop_user:Tn1C6kbjuEYxDmMHFGeG7yLh7QNzLWoM@dpg-d700qfk50q8c739tssg0-a.oregon-postgres.render.com/p2p_shop
