# Generated by Django 4.2.29 on 2026-03-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_promotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('method_type', models.CharField(choices=[('gateway', 'Payment Gateway (Razorpay)'), ('upi', 'Direct UPI (QR Code)'), ('cod', 'Cash on Delivery')], default='upi', max_length=20)),
                ('icon', models.CharField(blank=True, default='💳', max_length=20)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('upi_id', models.CharField(blank=True, max_length=100)),
                ('instructions', models.TextField(blank=True, help_text='Instructions for the customer')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
