# Generated by Django 4.2.29 on 2026-03-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_maincategory_image_productcategory_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(default='About Pixels to Plastic', max_length=200)),
                ('about_text', models.TextField(default='Crafted with Precision in India. Miniatures, tools and home décor — each piece uniquely printed to order.')),
                ('contact_email', models.EmailField(default='contact@p2p.com', max_length=254)),
                ('contact_phone', models.CharField(default='+91 98765 43210', max_length=20)),
                ('contact_address', models.TextField(default='Chennai, Tamil Nadu, India')),
                ('footer_copy', models.CharField(default='© 2026 Pixels to Plastic (P2P) | Crafted with Precision in India', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
